from __future__ import annotations
from typing import Dict, Iterator, Iterable, Tuple, Optional

# --- stdlib ---
import json
import re
import time
from pathlib import Path
from urllib.parse import urlparse, urlunparse, urljoin

# --- third-party ---
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from bs4 import BeautifulSoup
import usaddress  # declared in requirements.txt

# ==============================
# Basic config & tiny logger
# ==============================

DATA_DIR = Path("data"); DATA_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = DATA_DIR / "scraper.log"

def _log(line: str) -> None:
    try:
        LOG_PATH.write_text((LOG_PATH.read_text(encoding="utf-8") if LOG_PATH.exists() else "") + line.rstrip() + "\n", encoding="utf-8")
    except Exception:
        # Keep logging fire-and-forget; never break scraping
        pass

# ==============================
# HTTP session (UA + retries)
# ==============================

_UA_CHROME = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0 Safari/537.36"
)
_COMMON_HEADERS = {
    "User-Agent": _UA_CHROME,
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.8",
}

_SESSION: Optional[requests.Session] = None

def session() -> requests.Session:
    """Singleton session with browser-like headers and polite retries."""
    global _SESSION
    if _SESSION is None:
        s = requests.Session()
        s.headers.update(_COMMON_HEADERS)
        adapter = HTTPAdapter(
            max_retries=Retry(
                total=3,
                backoff_factor=0.3,
                status_forcelist=(429, 500, 502, 503, 504),
                allowed_methods=("HEAD", "GET"),
                raise_on_status=False,
            )
        )
        s.mount("http://", adapter)
        s.mount("https://", adapter)
        _SESSION = s
    return _SESSION

def variants(u: str) -> list[str]:
    """Return http/https and www/non-www variants (deduped, stable order)."""
    try:
        p = urlparse(u)
    except Exception:
        return [u]
    outs = [u]
    if p.scheme in {"http", "https"}:
        other = "https" if p.scheme == "http" else "http"
        outs.append(urlunparse(p._replace(scheme=other)))
    host = p.netloc
    if host:
        outs.append(urlunparse(p._replace(netloc=("www."+host) if not host.startswith("www.") else host[4:])))
    seen, uniq = set(), []
    for x in outs:
        if x not in seen:
            seen.add(x); uniq.append(x)
    return uniq

# ==============================
# Block detection (URL & body)
# ==============================

BLOCKED_HOSTS: Tuple[str, ...] = ("akamai", "edgesuite.net", "cloudfront", "captcha")
BLOCK_MARKERS: Tuple[str, ...] = (
    "access denied",
    "request denied",
    "request forbidden",
    "generated by cloudfront",
    "request unsuccessful",
    "the requested url was rejected",
    "are you a human",
    "reference #",
)

def is_block_page(text: str) -> bool:
    t = (text or "")[:5000].lower()
    return any(m in t for m in BLOCK_MARKERS)

# ==============================
# Lightweight extractors
# ==============================

PHONE_RE = re.compile(r"""
    (?:(?:\+1[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4})
""", re.VERBOSE)

def normalize_phone(p: str) -> str:
    digits = re.sub(r"\D", "", p or "")
    if len(digits) == 11 and digits.startswith("1"):
        digits = digits[1:]
    if len(digits) == 10:
        return f"({digits[:3]}) {digits[3:6]}-{digits[6:]}"
    return (p or "").strip()

def _jsonld_addresses(soup: BeautifulSoup) -> list[Dict[str, str]]:
    out: list[Dict[str, str]] = []
    for tag in soup.select('script[type="application/ld+json"]'):
        try:
            data = json.loads(tag.string or "")
        except Exception:
            continue
        items: Iterable = data if isinstance(data, list) else [data]
        for obj in items:
            if not isinstance(obj, dict):
                continue
            addr = obj.get("address")
            if isinstance(addr, dict) and addr.get("@type") in {"PostalAddress", "Address"}:
                line = (addr.get("streetAddress") or "").strip()
                city = (addr.get("addressLocality") or "").strip()
                zipc = (addr.get("postalCode") or "").strip()
                if line or city or zipc:
                    out.append({"address_line": line, "city": city, "zip": zipc})
    return out

def _heuristic_address(text: str) -> Optional[Dict[str, str]]:
    try:
        tagged, _ = usaddress.tag(text)
    except Exception:
        return None
    line = " ".join(filter(None, [
        tagged.get("AddressNumber"),
        tagged.get("StreetNamePreDirectional"),
        tagged.get("StreetName"),
        tagged.get("StreetNamePostType"),
        tagged.get("OccupancyType"),
        tagged.get("OccupancyIdentifier"),
    ]))
    city = tagged.get("PlaceName", "") or ""
    zipc = tagged.get("ZipCode", "") or ""
    if line or city or zipc:
        return {"address_line": line, "city": city, "zip": zipc}
    return None

def _first_contact_link(base_url: str, soup: BeautifulSoup) -> Optional[str]:
    for a in soup.select("a[href]"):
        txt = (a.get_text() or "").strip().lower()
        if any(k in txt for k in ("contact", "about", "staff", "directory")):
            href = a.get("href") or ""
            if isinstance(href, str):
                return urljoin(base_url, href)
    return None

# ==============================
# Networking + parse orchestration
# ==============================

def fetch_page(url: str, backoff: float = 0.0) -> Tuple[Optional[requests.Response], str]:
    """Try a few variants with browser-like headers. Skip CDN block pages."""
    for cand in variants(url):
        try:
            if backoff:
                time.sleep(backoff)
            r = session().get(
                cand, timeout=(6, 12), allow_redirects=True, headers={"Referer": cand}
            )
            if any(h in r.url for h in BLOCKED_HOSTS) or is_block_page(r.text):
                _log(f"[BLOCKED] {url} -> {r.url}")
                continue
            if r.status_code >= 400:
                _log(f"[HTTP {r.status_code}] {cand}")
                continue
            return r, r.url
        except requests.RequestException as e:
            _log(f"[HTTP ERR] {cand}: {e}")
            continue
    return None, url

def parse_contact_info(resp: requests.Response, base_url: str, backoff: float = 0.0) -> Tuple[Optional[Dict[str, str]], set[str]]:
    """Extract phones + best address from a page, with one polite follow."""
    soup = BeautifulSoup(resp.text, "lxml")

    # phones (simple US format)
    phones = {normalize_phone(m.group()) for m in PHONE_RE.finditer(soup.get_text(" ", strip=True))}
    phones.discard("")

    # JSON-LD first
    addrs = _jsonld_addresses(soup)
    best = next(iter(addrs), None)

    # one follow if no address yet
    if not best:
        follow = _first_contact_link(base_url, soup)
        if follow:
            try:
                if backoff:
                    time.sleep(backoff)
                r2 = session().get(
                    follow, timeout=(6, 12), allow_redirects=True, headers={"Referer": base_url}
                )
                if any(h in r2.url for h in BLOCKED_HOSTS) or is_block_page(r2.text):
                    _log(f"[BLOCKED] {base_url} -> {r2.url}")
                elif r2.status_code < 400:
                    s2 = BeautifulSoup(r2.text, "lxml")
                    addrs2 = _jsonld_addresses(s2)
                    best = next(iter(addrs2), None) or _heuristic_address(s2.get_text(" ", strip=True))
            except requests.RequestException:
                pass

    # final fallback: heuristic on landing page
    if not best:
        best = _heuristic_address(soup.getText(" ", strip=True))

    return best, phones

def extract_contacts(url: str, backoff: float = 0.0) -> Dict[str, str]:
    """Fetch one agency site and return phones + postal address (best-effort)."""
    start = time.time()
    print(f"   ↳ visiting {url}")

    resp, final_url = fetch_page(url, backoff)
    if resp is None:
        print("⚠ request failed for all variants")
        return {"source": url, "phones": ""}

    best, phones = parse_contact_info(resp, final_url, backoff)

    out = {
        "address_line": (best or {}).get("address_line", ""),
        "city":         (best or {}).get("city", ""),
        "zip":          (best or {}).get("zip", ""),
        "phones":       "; ".join(sorted(phones)) if phones else "",
        "source":       final_url,
    }
    _log(f"[DONE {round(time.time()-start,2)}s] {final_url}")
    print(f"   ✅ done in {round(time.time() - start, 2)}s\n")
    return out

# ==============================
# Provider adapter (same API)
# ==============================

class CAPostParser:
    """Adapter used by the registry/CLI to enrich rows for ca_post."""
    def __init__(self, backoff: float = 0.0):
        self.backoff = backoff

    def parse(self, html: str = "", url: str = "") -> Iterator[Dict[str, str]]:
        if not url:
            return iter(())
        data = extract_contacts(url, backoff=self.backoff)
        if "website" not in data and "source" in data:
            data["website"] = data["source"]
        yield data

    def enrich(self, row: Dict[str, str]) -> Dict[str, str]:
        url = row.get("website") or row.get("source") or ""
        if not url:
            return row
        out = dict(row)
        out.update(extract_contacts(url, backoff=self.backoff))
        if "website" not in out and "source" in out:
            out["website"] = out["source"]
        return out
